apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicrypto-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicrypto-backend
  template:
    metadata:
      labels:
        app: bicrypto-backend
    spec:
      containers:
      - name: backend
        image: bicrypto-backend:latest  # Thay bằng image registry của bạn
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: bicrypto-config
              key: NODE_ENV
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "v5"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bicrypto-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bicrypto-secrets
              key: REDIS_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bicrypto-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /api/health  # Giả sử có health check endpoint
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: bicrypto-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP

